### ISSUE TITLE
Error: Cannot find module 'process'

### ISSUE THREAD

**Issue by mlowicki** [benwtr/terphite#3]
On MacOSX:

```
mlowicki:accounts mlowicki$ npm install -g terphite
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.24","npm":"2.11.2"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.11.2"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.11.2"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.11.2"})
/usr/local/bin/terphite -> /usr/local/lib/node_modules/terphite/bin/terphite
terphite@0.0.3 /usr/local/lib/node_modules/terphite
├── blessed@0.1.81
├── lodash@4.5.0
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@6.0.2, tough-cookie@2.2.1, mime-types@2.1.10, form-data@1.0.0-rc3, aws4@1.2.1, bl@1.0.3, hawk@3.1.3, har-validator@2.0.6, http-signature@1.1.1)
└── blessed-contrib@2.5.3 (ansi-term@0.0.1, memorystream@0.3.1, term-canvas@0.0.5, strip-ansi@3.0.1, marked@0.3.5, memory-streams@0.1.0, chalk@1.1.1, sparkline@0.1.2, map-canvas@0.1.5, drawille-canvas-blessed-contrib@0.1.2, picture-tube@0.0.4, marked-terminal@1.6.1)

mlowicki:local mlowicki$ ./bin/terphite http://graphite.stats.sync.ams.osa

module.js:340
    throw err;
          ^
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/terphite/index.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

```
mlowicki:local mlowicki$ ./bin/node --version
v4.3.1
mlowicki:local mlowicki$ ./bin/terphite --version

module.js:340
    throw err;
          ^
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/terphite/index.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by benwtr** [comment]
Based on that output, it looks like you have two versions of node installed and one is probably broken because the process module ships with node, somethings very wrong if you can't load it.

Notice your npm says its using node 0.10.24? 

the shebang line of the first npm script on your PATH might lead to an explanation-

```
# head -1 $(which npm)
```

or you can try running it in an isolated environment, like a docker container.

**Comment by mlowicki** [comment]
You're right. User error.
