### ISSUE TITLE
Unclear error messages when faced with resolution/connectivity errors

### ISSUE THREAD

**Issue by olof** [benwtr/terphite#4]
Hey, this looks like a really cool and useful tool! I build a docker image like

```Dockerfile
FROM node:stretch
RUN npm install -g terphite
ENTRYPOINT ["terphite"]
```

But I was unable to start it. This is what I get when starting, with or without arguments:

```
TypeError: Cannot read property 'length' of undefined
    at Request._callback (/usr/local/lib/node_modules/terphite/lib/composer.js:198:34)
    at self.callback (/usr/local/lib/node_modules/terphite/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.init (/usr/local/lib/node_modules/terphite/node_modules/request/request.js:273:17)
    at new Request (/usr/local/lib/node_modules/terphite/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/terphite/node_modules/request/index.js:53:10)
    at loadMetricsTree (/usr/local/lib/node_modules/terphite/lib/composer.js:195:9)
    at Terphite.module.exports.Terphite.composer (/usr/local/lib/node_modules/terphite/lib/composer.js:462:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/terphite/index.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

(Same generic error message, but not same location as #1.)

**Comment by olof** [comment]
Ok, troubleshooting this with tcpdump, this was some kind of dns resolution failure/connection failure (8.8.8.8 was used for resolution within the docker container for some reason). I got it working. Feel free to close it, otherwise I rephrase it as an issue for improving error messages in case of network problems. Thanks for the cool tool!
